### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by AndrixRoot** [omp4j/omp4j#1]
Any Ideas for windows support? Need to install scala? or just install scala plugin in Netbeans IDE? thanks

**Comment by petrbel** [comment]
Hi! It really depends on what you're going to do - basically there are two approaches:
1. You want to use the preprocessor (i.e. simply translate some java sources) - in that case simply [download](http://www.omp4j.org/download) the `.jar` file. It is completely scala-free so regular java runtime env. is enough.
2. You want to hack into the preprocessor, tune it a little etc. In that case you are going to compile it by yourself hence you need scala environment as well.

I recommend you the prior way first :) It should be rather simple to use. Also please check the [project website](http://www.omp4j.org/) where you may find some examples and also a live demo.

I haven't tested the windows support much since I'm more unix-oriented, so in any case please let me know whether it works as expected and how you feel about the program :) Petr
