### ISSUE TITLE
execution with my own jar file

### ISSUE THREAD

**Issue by ghost** [omp4j/omp4j#3]
Hi

I am running my program using executable jar file after compiling with maven.

I want to use omp4j in my program.

How can I do so?

I know how to compile a single java file but I want more than that.

Thanks in advance

**Comment by petrbel** [comment]
Hey,
could you post a minimal working example? I haven't worked on the project for some time but I believe that multiple files are supported. I've tested that on some trivial examples without any problem..

**Comment by ghost** [comment]
So what I mean is that I run my program as follows:

java -jar myprogram.jar

This "myprogram.jar" file is made from maven compile.

Is there a way to use omp4j for my case?

**Comment by petrbel** [comment]
Oh I see, I didn't understand correctly what you were asking.
There are few points worth mentioning:
- `omp4j` is a source-code preprocessor, hence you can't use it on already compiled jars. It accepts only `.java` files as the input to be preprocessed.
- `omp4j` may be easily employed instead of `javac`. That leads to my hypothesis (I am not familiar with maven in much depth) that maven could be configured to use `omp4j` instead of `javac`. In any case, one may install `omp4j` and rename it as `javac` in order to force maven to use it.

So there is a simple answer to your question - yes, you may use it as long as you have the source files of your project and you compile the final jar by using `omp4j`.

I hope it explained everything :)
